#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

BINARYDIR := Debug

#Toolchain
CC := C:/SysGCC/mingw64/bin/gcc.exe
CXX := C:/SysGCC/mingw64/bin/g++.exe
LD := $(CXX)
AR := C:/SysGCC/mingw64/bin/ar.exe
OBJCOPY := C:/SysGCC/mingw64/bin/objcopy.exe

#Additional flags
PREPROCESSOR_MACROS := DEBUG=1
INCLUDE_DIRS := C:/msys64/mingw64/include C:/msys64/mingw64/include/glib-2.0 C:/msys64/mingw64/include/gtk-2.0 C:/msys64/mingw64/lib/glib-2.0/include C:/msys64/home/midwa/prefix/include/gimp-2.0 C:/msys64/home/midwa/prefix/include/gegl-0.3 C:/msys64/home/midwa/prefix/include/babl-0.1 C:/msys64/mingw64/include/cairo C:/msys64/mingw64/include/gdk-pixbuf-2.0 C:/msys64/mingw64/lib/gtk-2.0/include C:/msys64/mingw64/include/atk-1.0 C:/msys64/mingw64/include/pango-1.0
LIBRARY_DIRS := 
LIBRARY_NAMES := 
ADDITIONAL_LINKER_INPUTS := 
MACOS_FRAMEWORKS := 
LINUX_PACKAGES := 

CFLAGS := -ggdb -ffunction-sections -O0
CXXFLAGS := -ggdb -ffunction-sections -O0
ASFLAGS := 
LDFLAGS := -Wl,-gc-sections
COMMONFLAGS := 
LINKER_SCRIPT := 

START_GROUP := -Wl,--start-group
END_GROUP := -Wl,--end-group

#Additional options detected from testing the toolchain
USE_DEL_TO_CLEAN := 1
CP_NOT_AVAILABLE := 1
